name: flutter

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ADDRESS}}

    steps:
      - uses: actions/checkout@v3   
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' 
      - run: flutter upgrade    
      - run: flutter config --enable-web    
      - run: flutter devices
      - run: flutter pub add flutter_dotenv
      - run: flutter pub get
      - run: flutter build web -release

      
