name: flutter

on:
  push:
    branches: 
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ADDRESS}}

    steps:
      - uses: actions/checkout@v3   
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' 
      - run: flutter upgrade    
      - run: flutter config --enable-web    
      - run: flutter devices
      - run: flutter pub add flutter_dotenv
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git status
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f

      
